### ISSUE TITLE
Image file sizes quite big

### ISSUE THREAD

**Issue by rachaelcodes** [fac-12/facd-todo#40]
The image in your background looks fantastic, but it is quite big for a website image. Also, if you don't need the larger image, it's a good idea to remove it from the repo - it made cloning take a long time, which could be problematic with a bad connection. 

Here's an article with advice on image file sizes: http://awarecreativesolutions.com/optimize-images-for-web . I've used Preview on Mac* or Gimp (an open-source Photoshop alternative) to resize images, though there are probably good online tools - maybe ask in one of the general FAC Gitter channels to see if anyone has any recommendations.

*To do this, go to 'Export', choose JPEG and you can adjust the slider tool for image size. Needless to say, this isn't the most sophisticated way of doing it.

**Comment by AbdullahChaudhry** [comment]
You can also use https://imageoptim.com

**Comment by DevGrrrl** [comment]
Thanks, I thought they were fine under 1mb, but the doc says max 75-100kb, so I've just reduced the quality in photoshop. I think the image looks lightly pixelated now, but maybe this is fine? Haven't pushed it yet, but will do. 

Thanks for the tips!
