### ISSUE TITLE
.gitignore npm packages

### ISSUE THREAD

**Issue by rachaelcodes** [fac-12/facd-todo#41]
Don't forget to include a .gitignore in your files - people cloning your repo shouldn't have to download the node packages folder, when they can install everything using `npm install`.

If you've found it's taken a long time to download your repo from GitHub, this is probably why.

**Comment by AbdullahChaudhry** [comment]
When creating your repo in GitHub you can add Node to the .gitignore file like so: 

![screen shot 2017-11-03 at 10 55 46](https://user-images.githubusercontent.com/19255312/32370601-9f49570e-c085-11e7-8e1f-873b1526abc8.png)

**Comment by caralemony** [comment]
Thanks guys that has been done!
