### ISSUE TITLE
tidy up unfinished tests

### ISSUE THREAD

**Issue by rachaelcodes** [fac-12/facd-todo#44]
I'm sure you know that you have a failing test for your sort ToDo function. 

If you've unfinished functions/tests, it's best to have them kept in a different branch, which makes your finished code easier to read. (And also helps you get the credit you deserve for what you've done! :) )

**Comment by Dragomirc** [comment]
All fixed now. It was my type on one of the property of the objects the value was different than it should be.
I didn't realise it as we've been sorting on a different property.
