### ISSUE TITLE
Adding long ToDos

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/facd-todo#45]
Hey guys, looks awesome!

I tested adding a really long todo (because I'm mean 😂). Your app wraps the text really well! Just one small suggestion, could you have the tick / cross buttons at the top of the text rather than in the middle? With a really long todo, it might be easier for user to have buttons at the top of the text:

<img width="288" alt="screen shot 2017-11-03 at 10 13 25" src="https://user-images.githubusercontent.com/18463718/32369169-2b7ed024-c080-11e7-80f8-dc0e2a95171f.png">

**Comment by caralemony** [comment]
Thank you for the suggestion, it could be something to consider at a later date but we have decided to keep it the way it is for now.
