### ISSUE TITLE
Using innerHTML()

### ISSUE THREAD

**Issue by jamiecoe** [fac-12/facd-todo#55]
Sorry guys, I had to call it 😂 

In `dom.js` line 30 & 42,

It might be safer to make the <i> a seperate element and append it as a child to the button:
```
var icon = document.createElement('i');
icon.className = 'fa fa-times';
icon.setAttribute('aria-hidden',"true");
deleteButtonNode.appendChild(icon)
```

**Comment by Gbaja** [comment]
Thank you for your suggestion Jamie. 
We did it like that because we were using font-awesome but I do think we can do it this way aswell, something to consider for next time
