### ISSUE TITLE
This site is lol (great)

### ISSUE THREAD

**Issue by maxgerber** [fac-12/facd-todo#57]
I'm getting secondary school flashbacks with this crumpled paper effect, love it. A couple of styling 
suggestions...
+ Did you consider making the input text background transparent? I think it would add to the illusion.
+ I would love to see a handwriting font for this (ditto)

**Comment by Gbaja** [comment]
Thank you for your comments. 

We did consider making the input text background transparent but we concluded that we want it to be clear. 

RE:Handwriting - We were going for class and sophistication 🍸
